#!/usr/bin/env python
"""Export stable, TypeScript-facing contract artifacts from an AMA compile.

The AMA compiler (``amdl compile``) produces a rich native output tree. This
script maps that output to a small, stable, deterministically-named set of
artifacts that the TypeScript side consumes — so TS never imports Python.

Inputs  (an AMA output dir, e.g. ``generated/architecture``):
    ama-manifest.json, registry/meta-registry.json, graph/meta-graph.json,
    contracts/domain.ts, agents/*.json, workflows/*.json, api/openapi.json,
    schema/supabase-migration.sql, report/compile-report.json,
    catalog/event-catalog.json, catalog/policy-catalog.json

Outputs:
    <generated>/architecture-manifest.json
    <generated>/registry.json                (compact object index)
    <generated>/domain-graph.json
    <generated>/agents.generated.json
    <generated>/workflows.generated.json
    <generated>/openapi.generated.yaml
    <generated>/database-proposal.sql
    <generated>/compilation-report.json
    <generated>/events-catalog.json
    <generated>/policies-catalog.json
    <contracts>/contracts.generated.ts
    <contracts>/events.generated.ts
    <contracts>/permissions.generated.ts

Everything is deterministic (sorted keys, stable ordering); the only volatile
field of the raw compile (``generated_at``) is dropped from the stable
manifest.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

HEADER_TS = (
    "// GENERATED by AMA/AMDL from specifications/averro. DO NOT EDIT.\n"
    "// Regenerate with: npm run ama:compile\n"
)


def _read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def export(architecture: Path, generated: Path, contracts: Path) -> dict[str, str]:
    manifest = _read_json(architecture / "ama-manifest.json")
    registry = _read_json(architecture / "registry" / "meta-registry.json")
    fingerprint = manifest.get("fingerprint", "")
    objects = registry.get("objects", [])

    # 1. Stable architecture manifest (drop the volatile timestamp).
    stable_manifest = {k: v for k, v in manifest.items() if k != "generated_at"}
    stable_manifest["object_count"] = len(objects)
    _write_json(generated / "architecture-manifest.json", stable_manifest)

    # 2. Compact registry index (identity + audit metadata, no heavy bodies).
    compact = [
        {
            "fqid": o["fqid"],
            "kind": o["kind"],
            "id": o["id"],
            "domain": o.get("domain"),
            "name": o["value"].get("name", o["id"]),
            "version": o["value"].get("version"),
            "status": o["value"].get("status"),
        }
        for o in objects
    ]
    _write_json(generated / "registry.json", {"fingerprint": fingerprint, "objects": compact})

    # 3. Domain graph (already deterministic).
    _write_json(generated / "domain-graph.json", _read_json(architecture / "graph" / "meta-graph.json"))

    # 4. Agents bundle.
    agents_dir = architecture / "agents"
    agents = [
        _read_json(p)
        for p in sorted(agents_dir.glob("*.json"))
        if p.name != "index.json"
    ]
    _write_json(generated / "agents.generated.json", {"fingerprint": fingerprint, "agents": agents})

    # 5. Workflows bundle.
    wf_dir = architecture / "workflows"
    workflows = [_read_json(p) for p in sorted(wf_dir.glob("*.json"))]
    _write_json(generated / "workflows.generated.json", {"fingerprint": fingerprint, "workflows": workflows})

    # 6. OpenAPI as YAML.
    openapi = _read_json(architecture / "api" / "openapi.json")
    _write_text(
        generated / "openapi.generated.yaml",
        "# GENERATED by AMA/AMDL. DO NOT EDIT.\n"
        + yaml.safe_dump(openapi, sort_keys=True, allow_unicode=True),
    )

    # 7. Database proposal (additive-only SQL; proposal, never auto-applied).
    _write_text(
        generated / "database-proposal.sql",
        (architecture / "schema" / "supabase-migration.sql").read_text(encoding="utf-8"),
    )

    # 8. Compilation report + catalogs.
    _write_json(generated / "compilation-report.json", _read_json(architecture / "report" / "compile-report.json"))
    _write_json(generated / "events-catalog.json", _read_json(architecture / "catalog" / "event-catalog.json"))
    _write_json(generated / "policies-catalog.json", _read_json(architecture / "catalog" / "policy-catalog.json"))

    # 9. TypeScript contracts.
    domain_ts = (architecture / "contracts" / "domain.ts").read_text(encoding="utf-8")
    _write_text(
        contracts / "contracts.generated.ts",
        f"{HEADER_TS}// Architecture fingerprint: {fingerprint}\n\n"
        f'export const ARCHITECTURE_FINGERPRINT = "{fingerprint}";\n\n{domain_ts}',
    )
    _write_text(contracts / "events.generated.ts", _events_ts(objects, fingerprint))
    _write_text(contracts / "permissions.generated.ts", _permissions_ts(objects, fingerprint))

    return {"fingerprint": fingerprint, "objects": str(len(objects))}


def _events_ts(objects: list[dict], fingerprint: str) -> str:
    events = sorted(o["id"] for o in objects if o["kind"] == "event")
    union = " | ".join(json.dumps(e) for e in events) or "never"
    lines = [
        HEADER_TS,
        f'export const ARCHITECTURE_FINGERPRINT = "{fingerprint}";',
        "",
        f"export type EventId = {union};",
        "",
        "export const EVENT_IDS = [",
        *[f"  {json.dumps(e)}," for e in events],
        "] as const;",
        "",
    ]
    return "\n".join(lines)


def _permissions_ts(objects: list[dict], fingerprint: str) -> str:
    permissions = sorted(o["id"] for o in objects if o["kind"] == "permission")
    roles = sorted((o for o in objects if o["kind"] == "role"), key=lambda o: o["id"])
    perm_union = " | ".join(json.dumps(p) for p in permissions) or "never"
    role_union = " | ".join(json.dumps(r["id"]) for r in roles) or "never"
    lines = [
        HEADER_TS,
        f'export const ARCHITECTURE_FINGERPRINT = "{fingerprint}";',
        "",
        f"export type PermissionId = {perm_union};",
        f"export type RoleId = {role_union};",
        "",
        "export const PERMISSION_IDS = [",
        *[f"  {json.dumps(p)}," for p in permissions],
        "] as const;",
        "",
        "export const ROLE_PERMISSIONS: Record<RoleId, readonly PermissionId[]> = {",
        *[
            f"  {json.dumps(r['id'])}: [{', '.join(json.dumps(p) for p in r['value'].get('permissions', []))}],"
            for r in roles
        ],
        "};",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export stable AMA contract artifacts")
    parser.add_argument("--architecture", required=True, type=Path)
    parser.add_argument("--generated", required=True, type=Path)
    parser.add_argument("--contracts", required=True, type=Path)
    args = parser.parse_args()
    result = export(args.architecture, args.generated, args.contracts)
    print(f"Exported contracts (fingerprint {result['fingerprint']}, {result['objects']} objects)")


if __name__ == "__main__":
    main()
