from __future__ import annotations

import json
from collections.abc import Iterable
from html import escape
from typing import Any

import yaml

from .generator import GeneratedArtifact, GenerationContext, Generator
from .models import EntitySpec, FieldSpec, TypeSpec
from .security import highest_risk, scan_secrets, scan_sql
from .utils import kebab, plural, snake, write_json, write_text

HEADER = "<!-- Generated by AMA/AMDL. Edit the AMDL source, not this artifact. -->\n\n"


def _type_name(field: FieldSpec) -> str:
    kind = field.type.kind
    if kind in {"string", "text", "url", "email", "uuid", "date", "datetime", "money"}:
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "json":
        return "Record<string, unknown>"
    if kind == "array":
        return f"{field.type.items or 'unknown'}[]"
    if kind == "enum":
        return " | ".join(json.dumps(v) for v in field.type.values)
    if kind == "reference":
        return "string"
    if kind == "vector":
        return "number[]"
    return "unknown"


def _sql_type(field: FieldSpec) -> str:
    kind = field.type.kind
    return {
        "string": "text",
        "text": "text",
        "integer": "integer",
        "number": "numeric",
        "boolean": "boolean",
        "uuid": "uuid",
        "date": "date",
        "datetime": "timestamptz",
        "money": "numeric(14,2)",
        "url": "text",
        "email": "text",
        "json": "jsonb",
        "array": "jsonb",
        "enum": "text",
        "reference": "uuid",
        "vector": f"vector({field.type.dimensions or 1536})",
    }[kind]


def _table(entity: EntitySpec) -> str:
    return entity.table or plural(snake(entity.id))


def _entity_flags(context: GenerationContext, entity: EntitySpec) -> tuple[bool, bool, bool, bool]:
    defaults = context.document.defaults
    workspace = (
        defaults.workspace_scoped if entity.workspace_scoped is None else entity.workspace_scoped
    )
    audited = defaults.audited if entity.audited is None else entity.audited
    versioned = defaults.versioned if entity.versioned is None else entity.versioned
    soft_delete = defaults.soft_delete if entity.soft_delete is None else entity.soft_delete
    return workspace, audited, versioned, soft_delete


def _field_json_schema(type_spec: TypeSpec) -> dict[str, Any]:
    """Map an AMDL ``TypeSpec`` to a JSON Schema / OpenAPI schema fragment."""
    kind = type_spec.kind
    if kind in {"integer"}:
        return {"type": "integer"}
    if kind in {"number", "money"}:
        return {"type": "number"}
    if kind == "boolean":
        return {"type": "boolean"}
    if kind in {"json"}:
        return {"type": "object", "additionalProperties": True}
    if kind in {"array", "vector"}:
        return {"type": "array", "items": {"type": "number" if kind == "vector" else "string"}}
    schema: dict[str, Any] = {"type": "string"}
    if kind in {"uuid", "reference"}:
        schema["format"] = "uuid"
    elif kind == "date":
        schema["format"] = "date"
    elif kind == "datetime":
        schema["format"] = "date-time"
    elif kind == "url":
        schema["format"] = "uri"
    elif kind == "email":
        schema["format"] = "email"
    elif kind == "enum":
        schema["enum"] = type_spec.values
    return schema


class RegistryGenerator(Generator):
    name = "registry"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        path = context.output_dir / "registry" / "meta-registry.json"
        write_json(path, context.registry.to_dict())
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "registry")


class GraphGenerator(Generator):
    name = "graph"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        json_path = context.output_dir / "graph" / "meta-graph.json"
        mermaid_path = context.output_dir / "graph" / "meta-graph.mmd"
        write_text(json_path, context.graph.to_json() + "\n")
        write_text(mermaid_path, context.graph.to_mermaid())
        yield GeneratedArtifact(str(json_path.relative_to(context.output_dir)), "graph")
        yield GeneratedArtifact(str(mermaid_path.relative_to(context.output_dir)), "diagram")


class BlueprintGenerator(Generator):
    name = "blueprint"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        doc = context.document
        index_lines = [
            HEADER,
            f"# {doc.metadata.name} — Enterprise Blueprint\n",
            f"> Version {doc.metadata.version} · AMDL {doc.amdl}\n",
            doc.metadata.description + "\n",
            "## Domains\n",
        ]
        for domain in doc.domains:
            index_lines.append(
                f"- [{domain.name}](domains/{kebab(domain.id)}.md) — {domain.description}"
            )
        index_path = context.output_dir / "blueprint" / "README.md"
        write_text(index_path, "\n".join(index_lines) + "\n")
        yield GeneratedArtifact(str(index_path.relative_to(context.output_dir)), "blueprint")

        for domain in doc.domains:
            lines = [
                HEADER,
                f"# Domain Blueprint — {domain.name}\n",
                domain.description + "\n",
                f"**Owner:** {domain.owner or 'Unassigned'}  ",
                f"**Dependencies:** {', '.join(domain.depends_on) or 'None'}\n",
            ]
            sections: list[tuple[str, list[Any]]] = [
                ("Capabilities", domain.capabilities),
                ("Entities", domain.entities),
                ("Value Objects", domain.value_objects),
                ("Use Cases", domain.use_cases),
                ("Events", domain.events),
                ("Policies", domain.policies),
                ("Workflows", domain.workflows),
                ("Agents", domain.agents),
                ("Tools", domain.tools),
                ("Integrations", domain.integrations),
                ("API Resources", domain.api_resources),
                ("UI Surfaces", domain.ui_surfaces),
                ("Metrics", domain.metrics),
                ("Permissions", domain.permissions),
                ("Roles", domain.roles),
                ("Feature Flags", domain.feature_flags),
                ("Deployment Targets", domain.deployment_targets),
                ("Evaluations", domain.evaluations),
                ("Test Specs", domain.test_specs),
            ]
            for title, items in sections:
                lines.append(f"## {title}\n")
                if not items:
                    lines.append("_None declared._\n")
                    continue
                for item in items:
                    lines.append(f"### {item.name} (`{item.id}`)\n")
                    description = getattr(item, "description", "")
                    if description:
                        lines.append(description + "\n")
                    payload = item.model_dump(
                        mode="json", exclude={"id", "name", "description"}, exclude_none=True
                    )
                    if payload:
                        lines.append("```yaml")
                        lines.append(
                            yaml.safe_dump(payload, sort_keys=False, allow_unicode=True).rstrip()
                        )
                        lines.append("```\n")
            path = context.output_dir / "blueprint" / "domains" / f"{kebab(domain.id)}.md"
            write_text(path, "\n".join(lines) + "\n")
            source_ids = tuple(f"domain:{domain.id}.{x.id}" for x in domain.entities)
            yield GeneratedArtifact(
                str(path.relative_to(context.output_dir)), "blueprint", source_ids
            )


class SchemaGenerator(Generator):
    name = "schema"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        lines = [
            "-- Generated by AMA/AMDL. Review before applying.",
            "-- Non-destructive baseline: CREATE TABLE/INDEX/POLICY only.",
            "begin;",
            "create extension if not exists pgcrypto;",
            "create extension if not exists vector;",
            "",
        ]
        for domain in context.document.domains:
            lines.append(f"-- Domain: {domain.name}")
            for entity in domain.entities:
                workspace, audited, versioned, soft_delete = _entity_flags(context, entity)
                table = _table(entity)
                columns = ["  id uuid primary key default gen_random_uuid()"]
                if workspace:
                    columns.append(
                        "  workspace_id uuid not null references public.workspaces(id) on delete cascade"
                    )
                for field in entity.fields:
                    col = f"  {snake(field.name)} {_sql_type(field)}"
                    if field.required:
                        col += " not null"
                    if field.unique:
                        col += " unique"
                    if field.default is not None:
                        if isinstance(field.default, bool):
                            default = "true" if field.default else "false"
                        elif isinstance(field.default, (int, float)):
                            default = str(field.default)
                        else:
                            default = "'" + str(field.default).replace("'", "''") + "'"
                        col += f" default {default}"
                    if field.type.kind == "enum" and field.type.values:
                        values = ", ".join(
                            "'" + value.replace("'", "''") + "'" for value in field.type.values
                        )
                        col += f" check ({snake(field.name)} in ({values}))"
                    if field.type.kind == "reference" and field.type.target:
                        target = context.registry.resolve(field.type.target, {"entity"})
                        if target:
                            target_table = _table(target.value)
                            col += f" references public.{target_table}(id)"
                    columns.append(col)
                if entity.states and not any(f.name == "status" for f in entity.fields):
                    values = ", ".join(f"'{state}'" for state in entity.states)
                    columns.append(
                        f"  status text not null default '{entity.states[0]}' check (status in ({values}))"
                    )
                columns.extend(
                    [
                        "  version integer not null default 1",
                        "  metadata jsonb not null default '{}'::jsonb",
                        "  created_at timestamptz not null default now()",
                        "  updated_at timestamptz not null default now()",
                    ]
                )
                if audited:
                    columns.extend(
                        [
                            "  created_by uuid references auth.users(id)",
                            "  updated_by uuid references auth.users(id)",
                            "  created_by_agent_id uuid",
                            "  correlation_id uuid",
                        ]
                    )
                if soft_delete:
                    columns.append("  deleted_at timestamptz")
                lines.append(
                    f"create table if not exists public.{table} (\n" + ",\n".join(columns) + "\n);"
                )
                for field in entity.fields:
                    if field.indexed:
                        lines.append(
                            f"create index if not exists idx_{table}_{snake(field.name)} on public.{table} ({snake(field.name)});"
                        )
                for index in entity.indexes:
                    unique = "unique " if index.unique else ""
                    fields = ", ".join(snake(f) for f in index.fields)
                    lines.append(
                        f"create {unique}index if not exists {snake(index.name)} on public.{table} using {index.method} ({fields});"
                    )
                if workspace:
                    lines.extend(
                        [
                            f"alter table public.{table} enable row level security;",
                            f'drop policy if exists "workspace members read {table}" on public.{table};',
                            f'create policy "workspace members read {table}" on public.{table} for select using (public.is_workspace_member(workspace_id));',
                            f'drop policy if exists "workspace editors write {table}" on public.{table};',
                            f"create policy \"workspace editors write {table}\" on public.{table} for all using (public.has_workspace_role(workspace_id, array['owner','admin','editor'])) with check (public.has_workspace_role(workspace_id, array['owner','admin','editor']));",
                        ]
                    )
                if versioned:
                    version_table = f"{table}_versions"
                    lines.append(
                        f"create table if not exists public.{version_table} ("
                        "id uuid primary key default gen_random_uuid(), "
                        f"{snake(entity.id)}_id uuid not null references public.{table}(id) on delete cascade, "
                        "version integer not null, snapshot jsonb not null, change_reason text, "
                        "created_at timestamptz not null default now(), created_by uuid references auth.users(id), "
                        f"unique ({snake(entity.id)}_id, version));"
                    )
                lines.append("")
        lines.extend(["commit;", ""])
        path = context.output_dir / "schema" / "supabase-migration.sql"
        write_text(path, "\n".join(lines))
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "sql")


class OpenAPIGenerator(Generator):
    name = "openapi"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        paths: dict[str, Any] = {}
        schemas: dict[str, Any] = {}
        for domain in context.document.domains:
            for entity in domain.entities:
                schema_name = entity.name.replace(" ", "")
                properties: dict[str, Any] = {"id": {"type": "string", "format": "uuid"}}
                required: list[str] = []
                for field in entity.fields:
                    properties[field.name] = self._field_schema(field.type)
                    if field.description:
                        properties[field.name]["description"] = field.description
                    if field.required:
                        required.append(field.name)
                schemas[schema_name] = {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                }
            for resource in domain.api_resources:
                entity_entry = (
                    context.registry.resolve(resource.entity, {"entity"})
                    if resource.entity
                    else None
                )
                schema_name = (
                    entity_entry.value.name.replace(" ", "") if entity_entry else "CommandResult"
                )
                base = f"/api/{resource.version}{resource.path}"
                if "list" in resource.operations:
                    paths.setdefault(base, {})["get"] = self._operation(
                        resource, "list", schema_name
                    )
                if "create" in resource.operations or "execute" in resource.operations:
                    paths.setdefault(base, {})["post"] = self._operation(
                        resource, "create", schema_name
                    )
                detail = base + "/{id}"
                if "get" in resource.operations:
                    paths.setdefault(detail, {})["get"] = self._operation(
                        resource, "get", schema_name
                    )
                if "update" in resource.operations:
                    paths.setdefault(detail, {})["patch"] = self._operation(
                        resource, "update", schema_name
                    )
                if "archive" in resource.operations:
                    paths.setdefault(detail, {})["delete"] = self._operation(
                        resource, "archive", schema_name
                    )
        spec = {
            "openapi": "3.1.0",
            "info": {
                "title": context.document.metadata.name,
                "version": context.document.metadata.version,
                "description": context.document.metadata.description,
            },
            "servers": [{"url": "https://api.example.com"}],
            "security": [{"bearerAuth": []}],
            "paths": paths,
            "components": {
                "securitySchemes": {
                    "bearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}
                },
                "schemas": schemas,
            },
        }
        path = context.output_dir / "api" / "openapi.json"
        write_json(path, spec)
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "openapi")

    @staticmethod
    def _field_schema(type_spec: TypeSpec) -> dict[str, Any]:
        return _field_json_schema(type_spec)

    @staticmethod
    def _operation(resource, action: str, schema_name: str) -> dict[str, Any]:
        operation = {
            "operationId": f"{action}_{resource.id}".replace("-", "_"),
            "summary": f"{action.title()} {resource.name}",
            "tags": [resource.id],
            "responses": {"200": {"description": "Successful operation"}},
            "x-amdl-resource": resource.id,
        }
        if action in {"create", "update"}:
            operation["requestBody"] = {
                "required": True,
                "content": {
                    "application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}
                },
            }
        if action in {"get", "update", "archive"}:
            operation["parameters"] = [
                {
                    "name": "id",
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string", "format": "uuid"},
                }
            ]
        return operation


class TypeScriptGenerator(Generator):
    name = "typescript"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        lines = ["// Generated by AMA/AMDL. Do not edit directly.", ""]
        event_names: list[str] = []
        for domain in context.document.domains:
            lines.append(f"// Domain: {domain.name}")
            for entity in domain.entities:
                lines.append(f"export interface {entity.name.replace(' ', '')} {{")
                lines.append("  id: string;")
                workspace, audited, _, soft_delete = _entity_flags(context, entity)
                if workspace:
                    lines.append("  workspaceId: string;")
                for field in entity.fields:
                    optional = "" if field.required else "?"
                    lines.append(f"  {field.name}{optional}: {_type_name(field)};")
                if entity.states and not any(field.name == "status" for field in entity.fields):
                    lines.append(
                        "  status: " + " | ".join(json.dumps(x) for x in entity.states) + ";"
                    )
                lines.extend(
                    [
                        "  version: number;",
                        "  metadata: Record<string, unknown>;",
                        "  createdAt: string;",
                        "  updatedAt: string;",
                    ]
                )
                if audited:
                    lines.extend(
                        [
                            "  createdBy?: string;",
                            "  updatedBy?: string;",
                            "  createdByAgentId?: string;",
                        ]
                    )
                if soft_delete:
                    lines.append("  deletedAt?: string;")
                lines.append("}\n")
            for event in domain.events:
                event_names.append(event.id)
                type_name = "".join(part.title() for part in event.id.split("-"))
                lines.append(f"export interface {type_name}Event {{")
                lines.append(f"  type: {json.dumps(event.id)};")
                lines.append("  eventId: string;")
                lines.append("  workspaceId: string;")
                lines.append("  occurredAt: string;")
                lines.append("  correlationId: string;")
                lines.append("  payload: {")
                for field in event.payload:
                    optional = "" if field.required else "?"
                    lines.append(f"    {field.name}{optional}: {_type_name(field)};")
                lines.append("  };\n}\n")
        if event_names:
            types = [
                "".join(part.title() for part in name.split("-")) + "Event" for name in event_names
            ]
            lines.append("export type DomainEvent = " + " | ".join(types) + ";\n")
        path = context.output_dir / "contracts" / "domain.ts"
        write_text(path, "\n".join(lines))
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "typescript")


class AgentPromptGenerator(Generator):
    name = "agents"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        index: list[dict[str, Any]] = []
        for domain in context.document.domains:
            for agent in domain.agents:
                manifest = {
                    "schema_version": "1.0",
                    "id": agent.id,
                    "name": agent.name,
                    "domain": domain.id,
                    "role": agent.role,
                    "mission": agent.mission,
                    "capabilities": agent.capabilities,
                    "tools": agent.tools,
                    "event_subscriptions": agent.consumes,
                    "event_publications": agent.produces,
                    "policies": agent.policies,
                    "memory": agent.memory,
                    "budget": {"max_cost_per_run": agent.max_cost_per_run},
                    "approval_boundary": agent.approval_boundary,
                }
                path = context.output_dir / "agents" / f"{kebab(agent.id)}.json"
                write_json(path, manifest)
                prompt = self._prompt(domain, agent)
                prompt_path = context.output_dir / "prompts" / "agents" / f"{kebab(agent.id)}.md"
                write_text(prompt_path, prompt)
                index.append(
                    {
                        "id": agent.id,
                        "manifest": str(path.relative_to(context.output_dir)),
                        "prompt": str(prompt_path.relative_to(context.output_dir)),
                    }
                )
                yield GeneratedArtifact(
                    str(path.relative_to(context.output_dir)),
                    "agent",
                    (f"agent:{domain.id}.{agent.id}",),
                )
                yield GeneratedArtifact(
                    str(prompt_path.relative_to(context.output_dir)),
                    "prompt",
                    (f"agent:{domain.id}.{agent.id}",),
                )
        write_json(context.output_dir / "agents" / "index.json", index)
        yield GeneratedArtifact("agents/index.json", "agent-index")

    @staticmethod
    def _prompt(domain, agent) -> str:
        return (
            HEADER
            + f"""# System Prompt — {agent.name}

## Identity
You are **{agent.name}**, the {agent.role} for the **{domain.name}** domain.

## Mission
{agent.mission}

## Capabilities
{chr(10).join(f"- `{item}`" for item in agent.capabilities)}

## Authorized tools
{chr(10).join(f"- `{item}`" for item in agent.tools) or "- None"}

## Required policies
{chr(10).join(f"- `{item}`" for item in agent.policies) or "- Platform defaults"}

## Operating protocol
1. Read the task, workspace scope, evidence and approval boundary.
2. Produce a plan before invoking tools.
3. Cite the source or artifact used for every material conclusion.
4. Never cross workspace boundaries or expose secrets.
5. Do not perform external writes without the declared approval.
6. Return structured results, emitted events, costs and unresolved risks.
7. Record reusable learning only after quality review.

## Approval boundary
{agent.approval_boundary}
"""
        )


class WorkflowGenerator(Generator):
    name = "workflows"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        for domain in context.document.domains:
            for workflow in domain.workflows:
                payload = workflow.model_dump(mode="json")
                payload["domain"] = domain.id
                payload["schema_version"] = "1.0"
                path = context.output_dir / "workflows" / f"{kebab(workflow.id)}.json"
                write_json(path, payload)
                yield GeneratedArtifact(
                    str(path.relative_to(context.output_dir)),
                    "workflow",
                    (f"workflow:{domain.id}.{workflow.id}",),
                )


class UIManifestGenerator(Generator):
    name = "ui"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        surfaces: list[dict[str, Any]] = []
        for domain in context.document.domains:
            for surface in domain.ui_surfaces:
                entity = (
                    context.registry.resolve(surface.entity, {"entity"}) if surface.entity else None
                )
                fields = []
                states = []
                if entity:
                    fields = [field.model_dump(mode="json") for field in entity.value.fields]
                    states = entity.value.states
                surfaces.append(
                    {
                        **surface.model_dump(mode="json"),
                        "domain": domain.id,
                        "entity_schema": {"fields": fields, "states": states},
                        "permissions": ["workspace_member:view", "workspace_editor:mutate"],
                        "empty_state": f"No {surface.name.lower()} yet",
                        "loading_state": "skeleton",
                        "error_state": "retryable",
                    }
                )
        path = context.output_dir / "ui" / "surface-manifest.json"
        write_json(path, {"version": "1.0", "surfaces": surfaces})
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "ui-manifest")


class TestPlanGenerator(Generator):
    name = "test-plan"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        lines = [HEADER, "# Generated Verification Plan\n"]
        lines.append("## Global gates\n")
        lines.extend(
            [
                "- [ ] Schema validation succeeds.",
                "- [ ] Semantic validation has zero errors.",
                "- [ ] All workspace-scoped entities enforce tenant isolation.",
                "- [ ] External writes require authorization and an audit record.",
                "- [ ] Secrets never appear in generated artifacts or logs.",
                "- [ ] Migrations are forward-only and rollback has been reviewed.\n",
            ]
        )
        for domain in context.document.domains:
            lines.append(f"## {domain.name}\n")
            for use_case in domain.use_cases:
                lines.append(f"### `{use_case.id}`")
                lines.append(f"- [ ] Happy path implements `{use_case.capability}`.")
                lines.append("- [ ] Invalid input is rejected without partial writes.")
                lines.append("- [ ] Workspace boundary is tested with a second tenant.")
                lines.append(
                    "- [ ] Audit event contains actor, agent, correlation and cost metadata."
                )
                if use_case.approval == "required":
                    lines.append("- [ ] Execution pauses until human approval is recorded.")
                for event in use_case.emits:
                    lines.append(f"- [ ] Emits `{event}` exactly once with a versioned payload.")
                lines.append("")
            for workflow in domain.workflows:
                lines.append(f"### Workflow `{workflow.id}`")
                lines.append("- [ ] Every step is idempotent.")
                lines.append("- [ ] Retry, timeout, failure and escalation paths are covered.")
                lines.append("- [ ] Correlation ID is preserved through all steps.")
                lines.append("")
        path = context.output_dir / "tests" / "verification-plan.md"
        write_text(path, "\n".join(lines))
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "test-plan")


class ArchitectureExplorerGenerator(Generator):
    name = "explorer"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        data = context.registry.to_dict()
        encoded = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
        html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(context.document.metadata.name)} Architecture Explorer</title>
<style>
:root{{--bg:#0b0b0d;--panel:#151519;--panel2:#1d1d23;--text:#f7f7f8;--muted:#a7a7b0;--accent:#ff6a1a;--border:#2d2d35}}
*{{box-sizing:border-box}}body{{margin:0;font:14px/1.5 Inter,system-ui,sans-serif;background:var(--bg);color:var(--text)}}
header{{position:sticky;top:0;z-index:2;display:flex;gap:16px;align-items:center;padding:18px 24px;background:#0b0b0dee;border-bottom:1px solid var(--border);backdrop-filter:blur(14px)}}
.brand{{font-weight:800;font-size:18px}}.brand span{{color:var(--accent)}}input,select{{background:var(--panel);color:var(--text);border:1px solid var(--border);border-radius:10px;padding:10px 12px}}input{{flex:1;max-width:540px}}
main{{display:grid;grid-template-columns:280px 1fr;min-height:calc(100vh - 74px)}}aside{{padding:20px;border-right:1px solid var(--border)}}#stats{{color:var(--muted);margin-bottom:18px}}button{{display:block;width:100%;text-align:left;background:transparent;color:var(--muted);border:0;padding:9px 10px;border-radius:8px;cursor:pointer}}button:hover,button.active{{background:var(--panel2);color:var(--text)}}
section{{padding:24px}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}}.card{{background:linear-gradient(145deg,var(--panel),#111114);border:1px solid var(--border);border-radius:14px;padding:16px;min-height:150px}}.kind{{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--accent)}}h2{{margin:7px 0;font-size:17px}}.fqid{{font-family:ui-monospace,monospace;font-size:11px;color:var(--muted);word-break:break-all}}pre{{white-space:pre-wrap;color:#cfcfd5;font-size:11px;max-height:210px;overflow:auto}}@media(max-width:760px){{main{{grid-template-columns:1fr}}aside{{border-right:0;border-bottom:1px solid var(--border)}}}}
</style></head><body>
<header><div class="brand"><span>AMA</span> Architecture Explorer</div><input id="search" placeholder="Search domains, entities, events, agents…"><select id="domain"><option value="">All domains</option></select></header>
<main><aside><div id="stats"></div><div id="kinds"></div></aside><section><div id="grid" class="grid"></div></section></main>
<script id="registry" type="application/json">{encoded}</script>
<script>
const data=JSON.parse(document.getElementById('registry').textContent);const all=data.objects;let kind='';
const domains=[...new Set(all.map(x=>x.domain).filter(Boolean))].sort();const domain=document.getElementById('domain');domains.forEach(x=>domain.insertAdjacentHTML('beforeend',`<option>${{x}}</option>`));
const kinds=[...new Set(all.map(x=>x.kind))].sort();const kindsEl=document.getElementById('kinds');kindsEl.innerHTML='<button class="active" data-kind="">All objects</button>'+kinds.map(x=>`<button data-kind="${{x}}">${{x}}</button>`).join('');
const q=document.getElementById('search');function render(){{const term=q.value.toLowerCase();const selected=domain.value;const items=all.filter(x=>(!kind||x.kind===kind)&&(!selected||x.domain===selected)&&(!term||JSON.stringify(x).toLowerCase().includes(term)));document.getElementById('stats').textContent=`${{items.length}} of ${{all.length}} objects`;document.getElementById('grid').innerHTML=items.map(x=>`<article class="card"><div class="kind">${{x.kind}} · ${{x.domain||'global'}}</div><h2>${{x.value.name||x.id}}</h2><div class="fqid">${{x.fqid}}</div><pre>${{JSON.stringify(x.value,null,2)}}</pre></article>`).join('')}}
q.oninput=render;domain.onchange=render;kindsEl.onclick=e=>{{if(e.target.dataset.kind!==undefined){{kind=e.target.dataset.kind;[...kindsEl.children].forEach(x=>x.classList.remove('active'));e.target.classList.add('active');render()}}}};render();
</script></body></html>"""
        path = context.output_dir / "explorer" / "index.html"
        write_text(path, html)
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "html")


def _mermaid_id(node: str) -> str:
    return node.replace(":", "_").replace(".", "_").replace("-", "_")


class DependencyGraphGenerator(Generator):
    name = "dependency-graph"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        doc = context.document
        nodes = [{"id": f"domain:{d.id}", "label": d.name} for d in doc.domains]
        edges: list[dict[str, str]] = []
        for domain in doc.domains:
            for dep in sorted(domain.depends_on):
                edges.append(
                    {
                        "source": f"domain:{domain.id}",
                        "target": f"domain:{dep}",
                        "relation": "depends_on",
                    }
                )
        json_path = context.output_dir / "graph" / "dependency-graph.json"
        write_json(json_path, {"nodes": nodes, "edges": edges})
        mermaid = ["flowchart LR"]
        for node in nodes:
            mermaid.append(f'  {_mermaid_id(node["id"])}["{node["label"]}"]')
        for edge in edges:
            mermaid.append(f"  {_mermaid_id(edge['source'])} --> {_mermaid_id(edge['target'])}")
        mmd_path = context.output_dir / "graph" / "dependency-graph.mmd"
        write_text(mmd_path, "\n".join(mermaid) + "\n")
        yield GeneratedArtifact(str(json_path.relative_to(context.output_dir)), "graph")
        yield GeneratedArtifact(str(mmd_path.relative_to(context.output_dir)), "diagram")


class ImpactGraphGenerator(Generator):
    name = "impact-graph"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        graph = context.graph.graph
        adjacency = {
            node: {
                "kind": graph.nodes[node].get("kind"),
                "upstream": sorted(graph.predecessors(node)),
                "downstream": sorted(graph.successors(node)),
            }
            for node in sorted(graph.nodes)
        }
        path = context.output_dir / "graph" / "impact-graph.json"
        write_json(path, {"nodes": adjacency})
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "graph")


class JSONSchemaGenerator(Generator):
    name = "json-schema"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        index: list[dict[str, str]] = []
        for domain in context.document.domains:
            for entity in domain.entities:
                schema = self._entity_schema(context, domain.id, entity)
                rel = f"schema/json/{kebab(domain.id)}.{kebab(entity.id)}.schema.json"
                write_json(context.output_dir / rel, schema)
                index.append({"entity": f"{domain.id}.{entity.id}", "schema": rel})
                yield GeneratedArtifact(rel, "json-schema", (f"entity:{domain.id}.{entity.id}",))
        write_json(context.output_dir / "schema" / "json" / "index.json", {"schemas": index})
        yield GeneratedArtifact("schema/json/index.json", "json-schema-index")

    @staticmethod
    def _entity_schema(
        context: GenerationContext, domain_id: str, entity: EntitySpec
    ) -> dict[str, Any]:
        workspace, _audited, _versioned, soft_delete = _entity_flags(context, entity)
        properties: dict[str, Any] = {"id": {"type": "string", "format": "uuid"}}
        required: list[str] = ["id"]
        if workspace:
            properties["workspace_id"] = {"type": "string", "format": "uuid"}
            required.append("workspace_id")
        for field in entity.fields:
            schema = _field_json_schema(field.type)
            if field.description:
                schema["description"] = field.description
            properties[field.name] = schema
            if field.required:
                required.append(field.name)
        if entity.states and not any(f.name == "status" for f in entity.fields):
            properties["status"] = {"type": "string", "enum": list(entity.states)}
        properties["version"] = {"type": "integer"}
        properties["metadata"] = {"type": "object", "additionalProperties": True}
        properties["created_at"] = {"type": "string", "format": "date-time"}
        properties["updated_at"] = {"type": "string", "format": "date-time"}
        if soft_delete:
            properties["deleted_at"] = {"type": "string", "format": "date-time"}
        return {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": f"https://averro.dev/schema/{domain_id}/{entity.id}.json",
            "title": entity.name,
            "type": "object",
            "additionalProperties": False,
            "properties": properties,
            "required": required,
        }


class EventCatalogGenerator(Generator):
    name = "event-catalog"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        events: list[dict[str, Any]] = []
        for domain in context.document.domains:
            for event in domain.events:
                events.append(
                    {
                        "fqid": f"event:{domain.id}.{event.id}",
                        "id": event.id,
                        "name": event.name,
                        "domain": domain.id,
                        "aggregate": event.aggregate,
                        "schema_version": event.schema_version,
                        "producers": event.producers,
                        "consumers": event.consumers,
                        "payload": [f.model_dump(mode="json") for f in event.payload],
                    }
                )
        json_path = context.output_dir / "catalog" / "event-catalog.json"
        write_json(json_path, {"version": "1.0", "events": events})
        lines = [
            HEADER,
            "# Event Catalog\n",
            "| Event | Domain | Producers | Consumers |",
            "| --- | --- | --- | --- |",
        ]
        for row in events:
            lines.append(
                f"| `{row['id']}` | {row['domain']} | "
                f"{', '.join(row['producers']) or '—'} | {', '.join(row['consumers']) or '—'} |"
            )
        md_path = context.output_dir / "catalog" / "event-catalog.md"
        write_text(md_path, "\n".join(lines) + "\n")
        yield GeneratedArtifact(str(json_path.relative_to(context.output_dir)), "catalog")
        yield GeneratedArtifact(str(md_path.relative_to(context.output_dir)), "catalog")


class PolicyCatalogGenerator(Generator):
    name = "policy-catalog"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        policies: list[dict[str, Any]] = []
        for domain in context.document.domains:
            for policy in domain.policies:
                enforced_by = sorted(
                    f"use_case:{domain.id}.{uc.id}"
                    for uc in domain.use_cases
                    if policy.id in uc.policies
                )
                policies.append(
                    {
                        "fqid": f"policy:{domain.id}.{policy.id}",
                        "id": policy.id,
                        "name": policy.name,
                        "domain": domain.id,
                        "effect": policy.effect,
                        "enforcement": policy.enforcement,
                        "severity": policy.severity,
                        "condition": policy.condition,
                        "enforced_by": enforced_by,
                    }
                )
        json_path = context.output_dir / "catalog" / "policy-catalog.json"
        write_json(json_path, {"version": "1.0", "policies": policies})
        lines = [
            HEADER,
            "# Policy Catalog\n",
            "| Policy | Domain | Effect | Enforcement | Severity |",
            "| --- | --- | --- | --- | --- |",
        ]
        for row in policies:
            lines.append(
                f"| `{row['id']}` | {row['domain']} | {row['effect']} | "
                f"{row['enforcement']} | {row['severity']} |"
            )
        md_path = context.output_dir / "catalog" / "policy-catalog.md"
        write_text(md_path, "\n".join(lines) + "\n")
        yield GeneratedArtifact(str(json_path.relative_to(context.output_dir)), "catalog")
        yield GeneratedArtifact(str(md_path.relative_to(context.output_dir)), "catalog")


class ComponentManifestGenerator(Generator):
    name = "components"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        usage: dict[str, list[str]] = {}
        for domain in context.document.domains:
            for surface in domain.ui_surfaces:
                for component in surface.components:
                    usage.setdefault(component, []).append(f"ui_surface:{domain.id}.{surface.id}")
        components = [
            {"component": name, "used_by": sorted(surfaces)}
            for name, surfaces in sorted(usage.items())
        ]
        path = context.output_dir / "ui" / "component-manifest.json"
        write_json(path, {"version": "1.0", "components": components})
        yield GeneratedArtifact(str(path.relative_to(context.output_dir)), "component-manifest")


class GovernanceReportGenerator(Generator):
    """Scan generated artifacts for destructive or unsafe operations (ETAPA 8)."""

    name = "governance"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedArtifact]:
        findings = []
        sql_path = context.output_dir / "schema" / "supabase-migration.sql"
        if sql_path.exists():
            sql = sql_path.read_text(encoding="utf-8")
            findings.extend(scan_sql(sql))
            findings.extend(scan_secrets(sql, location="schema/supabase-migration.sql"))
        findings.extend(scan_secrets(json.dumps(context.registry.to_dict()), location="registry"))

        sensitive_fields = sorted(
            f"{domain.id}.{entity.id}.{field.name}"
            for domain in context.document.domains
            for entity in domain.entities
            for field in entity.fields
            if field.sensitive
        )
        non_isolated = sorted(
            f"{domain.id}.{entity.id}"
            for domain in context.document.domains
            for entity in domain.entities
            if (
                context.document.defaults.workspace_scoped
                if entity.workspace_scoped is None
                else entity.workspace_scoped
            )
            is False
            and entity.ownership != "system"
        )
        agent_boundaries = [
            {
                "agent": f"agent:{domain.id}.{agent.id}",
                "approval_boundary": agent.approval_boundary,
                "external_write_tools": [
                    t.id for t in domain.tools if t.id in agent.tools and t.external_writes
                ],
            }
            for domain in context.document.domains
            for agent in domain.agents
        ]
        report = {
            "version": "1.0",
            "overall_risk": highest_risk(findings),
            "destructive_operations": [f.to_dict() for f in findings],
            "requires_human_approval": any(f.requires_approval for f in findings),
            "migration_strategy": "additive-only (CREATE ... IF NOT EXISTS)",
            "sensitive_fields": sensitive_fields,
            "non_workspace_isolated_entities": non_isolated,
            "agent_approval_boundaries": agent_boundaries,
        }
        json_path = context.output_dir / "governance" / "governance-report.json"
        write_json(json_path, report)
        lines = [
            HEADER,
            "# Governance & Safety Report\n",
            f"- Overall risk: **{report['overall_risk']}**",
            f"- Destructive operations detected: **{len(findings)}**",
            f"- Requires explicit human approval: **{report['requires_human_approval']}**",
            f"- Migration strategy: `{report['migration_strategy']}`",
            f"- Sensitive fields tracked: **{len(sensitive_fields)}**",
            "",
            "This report is derived from the AMDL specification. The generated SQL is "
            "additive by construction; any destructive change (DROP, TRUNCATE, disabling "
            "RLS, unrestricted policies) is flagged here and must be approved by a human "
            "before it is applied. No SQL is applied automatically.",
            "",
        ]
        if findings:
            lines.extend(
                [
                    "## Flagged operations",
                    "",
                    "| Code | Risk | Location | Message |",
                    "| --- | --- | --- | --- |",
                ]
            )
            lines.extend(f"| {f.code} | {f.risk} | {f.location} | {f.message} |" for f in findings)
            lines.append("")
        else:
            lines.append("> No destructive operations or embedded secrets were detected.\n")
        md_path = context.output_dir / "governance" / "governance-report.md"
        write_text(md_path, "\n".join(lines))
        yield GeneratedArtifact(str(json_path.relative_to(context.output_dir)), "governance")
        yield GeneratedArtifact(str(md_path.relative_to(context.output_dir)), "governance")


BUILTIN_GENERATORS: list[Generator] = [
    RegistryGenerator(),
    GraphGenerator(),
    DependencyGraphGenerator(),
    ImpactGraphGenerator(),
    BlueprintGenerator(),
    SchemaGenerator(),
    JSONSchemaGenerator(),
    OpenAPIGenerator(),
    TypeScriptGenerator(),
    AgentPromptGenerator(),
    WorkflowGenerator(),
    UIManifestGenerator(),
    ComponentManifestGenerator(),
    EventCatalogGenerator(),
    PolicyCatalogGenerator(),
    TestPlanGenerator(),
    ArchitectureExplorerGenerator(),
    GovernanceReportGenerator(),
]
